services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fastbuy
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shared-network
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx-prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      api-prod:
        condition: service_healthy
    networks:
      - shared-network

  api-prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: backend
      target: production
      dockerfile: Dockerfile
    command: sh -c './bin/wait-for -t 0 mysqldb:3306 -- yarn start:prod'
    depends_on:
      - mysqldb
    networks:
      - shared-network
    ports:
      - 9000:9000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "http://nestjs_api_prod:9000"]
      interval: 5s
      timeout: 3s
      retries: 6

networks:
  shared-network:

volumes:
  db-config:
  db-data:
